services:
  web:
    build:
      context: .
      dockerfile: php.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./workspace/html:/var/www/html

  database:
    image: mysql:latest
    user: mysql
    environment:
      MYSQL_ROOT_PASSWORD: opencart
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: opencart
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
